# Generated by Django 2.2.5 on 2019-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=30, max_digits=100)),
                ('lon', models.DecimalField(decimal_places=30, max_digits=100)),
            ],
        ),
    ]
